FROM alpine:3.16

LABEL org.opencontainers.image.authors="u@skynetsingularity.com"
LABEL org.opencontainers.image.server_type="edge_server"

WORKDIR /app

RUN apk update
RUN apk add --no-cache python3 py3-pip nginx

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY edge_server/config/nginx.conf /etc/nginx/
COPY edge_server/web_content /var/www

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
