FROM nginx:1.21-alpine

RUN echo 'events { worker_connections 1024; }' > /etc/nginx/nginx.conf
COPY edge_server/config/nginx.conf /etc/nginx/conf.d/default.conf
COPY edge_server/web_content /var/www

